<a href="https://colab.research.google.com/github/srinijamorla/Pytorch-Learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**LISTS**

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.54841456, 0.43502225, 0.72705562, 0.98723336],
       [0.41607657, 0.13413961, 0.39468786, 0.36484849],
       [0.98811222, 0.89333142, 0.19820439, 0.02225298]])

TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.7414,  0.9553, -3.1579,  0.6728],
        [ 1.9260,  1.1635, -0.3519,  1.8069],
        [ 1.2396, -0.8813, -0.3758, -1.2545]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

In [7]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5484, 0.4350, 0.7271, 0.9872],
        [0.4161, 0.1341, 0.3947, 0.3648],
        [0.9881, 0.8933, 0.1982, 0.0223]], dtype=torch.float64)